- name: Drain nodes
  command: kubectl drain {{ item }} --delete-local-data --force --ignore-daemonsets
  loop: "{{ groups['all'] }}"
  ignore_errors: true

- name: Delete nodes
  command: kubectl delete node {{ item }}
  loop: "{{ groups['all'] }}"
  ignore_errors: true

- name: Reset kubeadm installed state
  command: kubeadm reset --force
  become: yes
