---
- name: "Build hosts file"
  lineinfile: 
    dest: /etc/hosts 
    regexp: '.*{{ item }}$' 
    line: "{{ hostvars[item].ansible_enp0s8.ipv4.address }} {{ item }}" 
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"
  tags:
    - hostfile
